version: "3"

services:
  database:
    container_name: mysql
    image: mariadb:latest #mac
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_DATABASE: InstagramDB
      TZ: 'Asia/Seoul'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${DB_PASSWORD} --silent" ]
      interval: 30s
      retries: 5

  web:
    container_name: instagram
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      url: ${LOCAL_DB_URL}
      username: ${LOCAL_DB_USERNAME}
      password: ${LOCAL_DB_PASSWORD}
    restart: always
    volumes:
      - app:/app
    networks:
      - network
    env_file:
      - .env

volumes:
  dbdata:
  app:

networks:
  network:
    driver: bridge
